# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 23:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_book', '0002_auto_20161027_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='priority',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
