# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 17:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import recipe_book.models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_book', '0004_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to=recipe_book.models.ingredient_image_location)),
                ('amount', models.FloatField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='IngredientAmount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe_book.Ingredient')),
            ],
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to=recipe_book.models.recipe_image_location),
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='ingredientamount',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe_book.Recipe'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(through='recipe_book.IngredientAmount', to='recipe_book.Ingredient'),
        ),
    ]
