# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_book', '0005_auto_20161101_1722'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='amount',
        ),
        migrations.AddField(
            model_name='ingredientamount',
            name='amount',
            field=models.FloatField(default=1),
        ),
    ]
