# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-04 19:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_book', '0009_auto_20161101_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='recipe_book.Recipe'),
        ),
    ]
